### ISSUE TITLE
It would be really nice to have a embedlr.remove() method

### ISSUE THREAD

**Issue by scottmas** [mollerse/gulp-embedlr#1]
Thanks for making this plugin, just one request. Could you add a remove() method? When writing to my production folder I would like to have a way to ensure that the code snippet is removed. 

One easy way would be to wrap the snippet in some comments like " [snippet] , and then do a regex replace on the file contents like so: fileContents.replace(/.*?/, "")

**Comment by mollerse** [comment]
The idea is that you don't modify your original file, which would mean that removing the modification would never be an issue because the original file was still pristine.

Dev workflow would look like this:
Original file --> embedlr --> build folder

While production workflow would look like this:
Original file --> build folder

One way to achieve this in the gulpfile would be to use something like gulp-util's noop-function

```
var gulp = require('gulp');
var gutil = require('gulp-util');
var embedlr = require('gulp-embedlr');

var production = process.env.type === 'production';

gulp.src('index.html')
  .pipe(production ? gutil.noop() : embedlr())
  .pipe(gulp.dest('build');
```
